//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsManagment.Models
{
    using Common;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class student
    {
        
        public int Id { get; set; }

        [Required(ErrorMessage ="First name field is required")]
        [RegularExpression(@"^[a-zA-Z\s]+$")]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "First name must be between 2 and 20")]
        public string First_name { get; set; }

        [Required(ErrorMessage = "Last name field is required")]
        [RegularExpression(@"^[a-zA-Z\s]+$")]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "Last name must be between 2 and 20")]
        public string Last_name { get; set; }

        [Required(ErrorMessage = "Birth date field is required")]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
        [DateValidator(ErrorMessage ="Date is invalid, difference between current year and date of birth must be 5 or more")]
        public System.DateTime Date_of_birth { get; set; }

        [Required(ErrorMessage = "Student id field is required")]
        [RegularExpression(@"^[0-9\b]+$")]
        [StringLength(9)]
        public string Student_id { get; set; }
        public string City { get; set; }
        [StringLength(1000)]
        public string Description { get; set; }
    }
}
